CREATE TABLE configs (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"domain" INT NOT NULL, 
mapTitle CHAR(100) NOT NULL,
openURL CHAR(100) NOT NULL,
appId INT NOT NULL,
token CHAR(100) NOT NULL,
centerLat INT NOT NULL,
centerLng INT NOT NULL,
marker CHAR(20) NOT NULL,
name CHAR(100) NOT NULL,
latitude CHAR(100) NOT NULL,
longitude CHAR(100) NOT NULL,
"group" CHAR(100) NOT NULL,
color CHAR(100) NOT NULL,
addImage CHAR(200) NOT NULL,
mapTile CHAR(100) NOT NULL,
creater CHAR(100) NOT NULL,
valid BOOLEAN NOT NULL,
foreign key ("domain") references domain(id)
);

SELECT * FROM benri_map_configs;

ALTER TABLE configs ALTER COLUMN mapTitle TYPE VARCHAR(100);
ALTER TABLE configs ALTER COLUMN openURL TYPE VARCHAR(100);
ALTER TABLE configs ALTER COLUMN token TYPE VARCHAR(100);
ALTER TABLE configs ALTER COLUMN marker TYPE VARCHAR(20);
ALTER TABLE configs ALTER COLUMN name TYPE VARCHAR(100);
ALTER TABLE configs ALTER COLUMN latitude TYPE VARCHAR(100);
ALTER TABLE configs ALTER COLUMN longitude TYPE VARCHAR(100);
ALTER TABLE configs ALTER COLUMN "group" TYPE VARCHAR(100);
ALTER TABLE configs ALTER COLUMN color TYPE VARCHAR(100);
ALTER TABLE configs ALTER COLUMN addImage TYPE VARCHAR(200);
ALTER TABLE configs ALTER COLUMN creater TYPE VARCHAR(100);

ALTER TABLE configs RENAME COLUMN mapTitle TO map_title;
ALTER TABLE configs RENAME COLUMN openURL TO open_url;
ALTER TABLE configs RENAME COLUMN appId TO app_id;
ALTER TABLE configs RENAME COLUMN centerLat TO center_lat;
ALTER TABLE configs RENAME COLUMN centerLng TO center_lng;
ALTER TABLE configs RENAME COLUMN addImage TO add_image;
ALTER TABLE configs RENAME COLUMN mapTile TO map_tile;
ALTER TABLE configs ALTER COLUMN map_tile TYPE VARCHAR(100);

ALTER TABLE configs ALTER COLUMN center_lat DROP NOT NULL;
ALTER TABLE configs ALTER COLUMN center_lat TYPE decimal
 USING CASE
  WHEN latitude = null THEN 0
  ELSE 0
 END;
ALTER TABLE configs ALTER COLUMN center_lat SET NOT NULL;
ALTER TABLE configs ALTER COLUMN center_lng DROP NOT NULL;
ALTER TABLE configs ALTER COLUMN center_lng TYPE decimal
 USING CASE
  WHEN latitude = null THEN 0
  ELSE 0
 END;
 ALTER TABLE configs ALTER COLUMN center_lng SET NOT NULL;
 
UPDATE configs SET creater = 1;
ALTER TABLE configs ALTER COLUMN creater DROP NOT NULL;
ALTER TABLE configs ALTER COLUMN creater TYPE INT
 USING CASE
  WHEN latitude = '' THEN 1
  ELSE 0
 END;
 ALTER TABLE configs ALTER COLUMN creater SET NOT NULL;
 DELETE FROM configs;
 
 ALTER TABLE configs RENAME TO benri_map_configs;

UPDATE benri_map_configs SET map_tile = 'open_street_map' WHERE map_tile = 'OpenStreetMap';
UPDATE benri_map_configs SET map_tile = 'digital_topographic_map' WHERE map_tile = '電子地形図';