select current_schema;

set search_path to "benri_map";

SELECT
    * 
FROM
    benri_map.customer_map 
    INNER JOIN benri_map.customers 
        ON benri_map.customer_map.contract_id = benri_map.customers.customer_id
;

CREATE TABLE customers (
customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
customer_name VARCHAR(100),
domain_id INT NOT NULL, 
foreign key (domain_id) references public.domain(id)
);

ALTER TABLE customers ADD COLUMN customer_name VARCHAR(100);
ALTER TABLE customer_map ADD COLUMN is_enabled BOOLEAN;

CREATE TABLE map_addon_subscriptions (
addon_sub_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
payment_type VARCHAR(50) NOT NULL,
addon_aub_price INT NOT NULL
);

CREATE TABLE subscription_billings (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
customer_id INT NOT NULL,
billing_period_start DATE NOT NULL,
billing_period_end DATE NOT NULL,
amount INT NOT NULL,
status VARCHAR(50) NOT NULL,
created_at TIMESTAMP WITHOUT TIME ZONE,
foreign key (customer_id) references customers(customer_id)
);
