-- 2段階認証コード用テーブル
CREATE TABLE auth_codes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    benri_map_user_id INTEGER REFERENCES benri_map_users(id) ON DELETE CASCADE NOT NULL,
    email VARCHAR(100) NOT NULL,
    code VARCHAR(6) NOT NULL,
    attempts INTEGER DEFAULT 0,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_used BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- テーブル本体へのコメント
COMMENT ON TABLE auth_codes IS 'メール認証・2段階認証用のコード管理テーブル';

-- 各カラムへのコメント
COMMENT ON COLUMN auth_codes.id IS 'id';
COMMENT ON COLUMN auth_codes.benri_map_user_id IS 'benri_map_user_id';
COMMENT ON COLUMN auth_codes.email IS 'コード送信先のメールアドレス';
COMMENT ON COLUMN auth_codes.code IS '6桁の認証コード';
COMMENT ON COLUMN auth_codes.attempts IS '認証試行回数';
COMMENT ON COLUMN auth_codes.expires_at IS 'コードの有効期限';
COMMENT ON COLUMN auth_codes.is_used IS '使用済みフラグ';
