CREATE TABLE domain (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"domain" char(20) NOT NULL, 
domainText char(50) NOT NULL,
openDomeinText char(60) NOT NULL
);

SELECT * FROM domain;

INSERT INTO "domain" ("domain", domainText, openDomainText) VALUES ('5uz7f776jav6', '8CloudsMap', '8CloudsPablicMap');

ALTER TABLE "domain" RENAME COLUMN openDomeinText TO openDomainText;

ALTER TABLE "domain" ALTER COLUMN "domain" TYPE VARCHAR(20);
ALTER TABLE "domain" ALTER COLUMN domainText TYPE VARCHAR(50);
ALTER TABLE "domain" ALTER COLUMN openDomainText TYPE VARCHAR(60);

ALTER TABLE "domain" RENAME COLUMN domainText TO domain_text;
ALTER TABLE "domain" RENAME COLUMN openDomainText TO open_domain_text;
UPDATE "domain" SET open_domain_text = '8CloudsPublicMap';