CREATE TABLE mapShowUsers (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
config INT NOT NULL, 
"user" INT NOT NULL, 
edit BOOLEAN NOT NULL,
"create" BOOLEAN NOT NULL,
setConfig BOOLEAN NOT NULL,
foreign key (config) references configs(id),
foreign key ("user") references users(id)
);

SELECT * FROM mapShowUsers;

ALTER TABLE mapShowUsers RENAME COLUMN setConfig TO set_config;

INSERT INTO mapShowUsers (config, "user", edit, "create", set_config) VALUES (1, 1, true, true, true);

DELETE FROM mapShowUsers;