CREATE TABLE narrowDown (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
config INT NOT NULL, 
field VARCHAR(100) NOT NULL,
"value" VARCHAR(200) NOT NULL,
andor VARCHAR(10) NOT NULL,
foreign key (config) references configs(id)
);

ALTER TABLE narrowDown ADD COLUMN condition VARCHAR(50);

SELECT * FROM narrowDown;

DELETE FROM narrowDown;