CREATE TABLE options (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"domain" INT NOT NULL, 
"option" char(50) NOT NULL,
valid BOOLEAN NOT NULL
);

INSERT INTO options ("domain", "option", valid) VALUES (1, 'addImage', true);
SELECT * FROM options;

ALTER TABLE options ADD FOREIGN KEY ("domain") 
REFERENCES "domain" (id);

SELECT * FROM options JOIN "domain" ON options.domain = domain.id;

ALTER TABLE options ALTER COLUMN "option" TYPE VARCHAR(50);

INSERT INTO options ("domain", "option", valid) VALUES (1, 'drawMap', true);

INSERT INTO benri_map_options ("domain", "option", valid) VALUES (1, 'addShapeFile', true);

ALTER TABLE options RENAME TO benri_map_options;
