CREATE TABLE users (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"domain" INT NOT NULL, 
userName char(100) NOT NULL,
userId char(100) NOT NULL,
email char(100) NOT NULL,
password char(100) NOT NULL,
foreign key ("domain") references domain(id)
);

INSERT INTO users ("domain", userName, userId, email, password) VALUES (1, 'admin', 'admin@example.com', '', md5('adminpass'));

SELECT * FROM users;

ALTER TABLE users ADD COLUMN authority INT;

UPDATE users SET authority = 0;

ALTER TABLE users ALTER COLUMN userName TYPE VARCHAR(100);
ALTER TABLE users ALTER COLUMN userId TYPE VARCHAR(100);
ALTER TABLE users ALTER COLUMN email TYPE VARCHAR(100);
ALTER TABLE users ALTER COLUMN password TYPE VARCHAR(100);

ALTER TABLE users RENAME COLUMN userId TO user_id;
ALTER TABLE users RENAME COLUMN userName TO user_Name;

DELETE FROM users WHERE id != 1;

SELECT users.* FROM users AS users JOIN domain ON users.domain = domain.id
      WHERE domain.domain_text = '8CloudsMap' AND users.user_id = 'takai-h1' AND users.password = md5('takaiPass');

ALTER TABLE users RENAME TO benri_map_users;